<?php

$countries = array(
  'iso' => 'fr',
  'name' => 'Français',
  'select' => 'Veuillez selectioner la langue et le pays du Site Maître:',
  'countries' => array(
     'ad' => 'Andorre',
     'be' => 'Belgique',
     'bj' => 'Bénin',
     'bf' => 'Burkina Faso',
     'bi' => 'Burundi',
     'cm' => 'Cameroun',
     'ca' => 'Canada',
     'cg' => 'Congo',
     'ci' => 'Côte d\'Ivoire',
     'km' => 'Comores',
     'dj' => 'Djibouti',
     'fr' => 'France',
     'ga' => 'Gabon',
     'gn' => 'Guinée',
     'gq' => 'Guinée Equatoriale',
     'ht' => 'Haïti',
     'lu' => 'Luxembourg',
     'mg' => 'Madagascar',
     'ml' => 'Mali',
     'mc' => 'Monaco',
     'ne' => 'Niger',
     'ng' => 'Nigéria',
     'cf' => 'République Centrafricaine',
     'cd' => 'République Démocratique du Congo',
     'rw' => 'Rwanda',
     'sn' => 'Sénégal',
     'sc' => 'Seychelles',
     'ch' => 'Suisse',
     'td' => 'Tchad',
     'tg' => 'Togo',
     'vu' => 'Vanuatu'
    )
  );

?>