<?php

$countries = array(
  'iso' => 'es',
  'name' => 'Español',
  'select' => 'Favor de escoger el idioma y el país del Sitio Maestro:',
  'countries' => array(
     'ar' => 'Argentina',
     'bz' => 'Belice',
     'bo' => 'Bolivia',
     'cl' => 'Chile',
     'co' => 'Colombia',
     'cr' => 'Costa Rica',
     'cu' => 'Cuba',
     'ec' => 'Ecuador',
     'sv' => 'El Salvador',
     'es' => 'España',
     'gt' => 'Guatemala',
     'gq' => 'Guinea Ecuatorial',
     'hn' => 'Honduras',
     'mx' => 'México',
     'ni' => 'Nicaragua',
     'pa' => 'Panamá',
     'py' => 'Paraguay',
     'pe' => 'Perú',
     'pr' => 'Puerto Rico',
     'do' => 'República Dominicana',
     'uy' => 'Uruguay',
     've' => 'Venezuela'
    )
  );

?>